# Generated by Django 4.2.16 on 2024-12-03 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_data', '0002_indicator_alter_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country1', models.CharField(max_length=100)),
                ('country2', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
